---
abstract: 'L<DBIx::Class::QueryLog> support for L<Catalyst::Model::DBIC::Schema>'
author:
  - 'Fayland Lam <fayland@gmail.com>'
generated_by: 'Dist::Zilla::Plugin::MetaYAML version 1.091610'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-TraitFor-Model-DBIC-Schema-QueryLog
requires:
  Catalyst::Component::InstancePerContext: 0
  Catalyst::Model::DBIC::Schema: 0.24
  DBIx::Class::QueryLog: 0
resources:
  repository: http://github.com/fayland/catalyst-traitfor-model-dbic-schema-querylog/tree
version: 0.01
